publicVerbs = 承认, 认可, 同意, 断言, 声称, 抱怨, 宣布, 否认, 解释, 暗示, 坚持, 提到, 宣称, 承诺, 抗议, 评论, 回复, 报道, 说, 建议, 发誓, 写道, 宣告, 发言, 通知, 回应
privateVerbs = 预期, 假设, 相信, 得出结论, 决定, 证明, 确定, 发现, 怀疑, 估计, 害怕, 感觉, 发现, 忘记, 猜测, 听到, 希望, 想象, 暗示, 表明, 推断, 知道, 学习, 意味着, 注意到, 证明, 意识到, 识别, 记得, 揭示, 看见, 显示, 假定, 认为, 理解
suasiveVerbs = 同意, 安排, 请求, 乞求, 命令, 决定, 要求, 授予, 坚持, 指示, 规定, 保证, 宣布, 提议, 建议, 请求, 规定, 建议, 敦促
generalEmphatics = 确实, 很多, 大多数, 非常
generalHedges = 也许, 大约, 类似, 或多或少, 有点, 某种程度上
firstPersonPronouns = 我, 我们, 我, 我们, 我的, 我们的, 我自己, 我们自己
secondPersonPronouns = 你, 你的, 你自己, 你们自己
thirdPersonPronouns = 她, 他, 他们, 她, 他, 他们, 他的, 他们的, 他自己, 她自己, 他们自己
itWord = 它, 它自己
subjectPronouns = 我, 我们, 他, 她, 他们
indefinitePronouns = 任何人, 任何一个人, 任何事物, 每个人, 所有人, 一切, 没有人, 无人, 没有东西, 无处, 某人, 某个人, 某事
demonstrativePronouns = 那个, 这个, 这些, 那些
placeAdverbials = 在船上, 在上方, 在国外, 穿过, 在前方, 在旁边, 在周围, 在岸上, 在后方, 离开, 在后面, 在下面, 在之下, 在旁边, 向下坡, 在楼下, 在下游, 东方, 远处, 在此附近, 在室内, 在内陆, 在近海, 在里面, 在本地, 在附近, 靠近, 北方, 无处, 在户外, 在外面, 在船外, 在陆地上, 在海外, 南方, 在脚下, 在地下, 在下面, 向上坡, 在楼上, 在上游, 西方
timeAdverbials = 之后, 再次, 更早, 早期, 最终, 从前, 立即, 最初, 立刻, 晚, 最近, 之后, 片刻, 现在, 如今, 曾经, 最初, 目前, 之前, 最近, 不久, 同时, 随后, 今天, 明天, 今晚, 昨天
possibilityModals = 能, 可以, 可能, 能够
necessityModals = 应该, 必须
predictionModals = 将, 会, 将会
whQuestions = 谁, 什么, 哪里, 何时, 如何, 是否, 为什么, 无论谁, 无论谁（宾格）, 无论哪个, 无论哪里, 无论何时, 无论什么
whMarkers = 什么, 哪里, 何时, 哪个, 谁, 谁的
amplifiers = 绝对地, 完全地, 彻底地, 极大地, 完全地, 极其, 充分地, 大大地, 高度地, 强烈地, 完美地, 强烈地, 彻底地, 完全地, 极其, 非常
downtoners = 几乎, 勉强, 几乎不, 仅仅, 略微, 接近, 只, 部分地, 局部地, 几乎, 几乎不, 略微, 有点
seemappear = 似乎, 看起来
quantifiers = 每个, 所有, 每一个, 许多, 很多, 少数, 几个, 一些, 任何
discourseParticles = 好吧, 现在, 不管怎样, 总之, 然而
concessives = 虽然, 尽管
conditionalSubordination = 如果, 除非
conjunctsSingle = 或者, 因此, 相反地, 例如, 此外, 因此, 然而, 即, 相反, 同样地, 而且, 即, 尽管如此, 仍然, 尽管, 否则, 类似地, 因此, 因此, 换言之, 相比之下, 特别是, 此外, 总之, 因此, 总而言之, 总结来说, 例如, 举例来说, 而不是, 相比之下, 比较而言, 无论如何, 在任何情况下, 换句话说, 因此, 结果, 相反地, 另一方面
conjunctsPUNCT = 否则, 完全地, 相当
osubordinators = 由于, 当…时, 当…时, 因而, 然而, 借此, 鉴于, 鉴于, 在…范围内, 在…程度上
sentenceRelatives = 这/该
piedPiping = 谁, 谁的, 哪个
clausePunctuation = 。,！,？,：,；,—
notWord = 不, 没有
neitherWord = 既不, 也不
becauseWord = 因为
doVerb = 做
beVerb = 是